import assert from "node:assert/strict";
import { AsyncLocalStorage } from "node:async_hooks";
import test from "node:test";
import { createAkentrosApiLimitStore } from "@akentros/core/apiLimits";
import { createAkentrosBillingStore } from "@akentros/core/billing";
import { createAkentrosProviderPoolStore } from "@akentros/core/providerPool";
import { PROVIDER_POOLS } from "@akentros/core/providers";
import type { AkentrosQuery } from "@akentros/core/query";
import { migrateAkentrosSchema } from "@akentros/core/schemaMigration";
import { PGlite } from "@electric-sql/pglite";

// PostgreSQL 方言的端到端驗證:以 @electric-sql/pglite(內嵌 PG16)跑
// 遷移 + 計費 reserve→settle/refund + provider pool claim/release +
// 金鑰 RPM/併發 acquire/release 的完整回路,釘死 core SQL 在 PG 方言下
// 的行為與 SQLite 一致(含 FOR UPDATE 行鎖與 advisory lock 語句)。

function normalizeParam(value: any): unknown {
  if (value === undefined) return null;
  if (typeof value === "boolean") return value ? 1 : 0;
  if (typeof value === "bigint") return value.toString();
  if (Array.isArray(value)) return JSON.stringify(value);
  if (value !== null && typeof value === "object") return JSON.stringify(value);
  return value;
}

function createPgliteQuery(db: PGlite): AkentrosQuery {
  const txStorage = new AsyncLocalStorage<{ db: PGlite }>();
  const query = (async (sql: string, params: any[] = []) => {
    const client = txStorage.getStore()?.db ?? db;
    let index = 0;
    const text = sql.replace(/\?/g, () => `$${++index}`);
    const result = await client.query(text, params.map(normalizeParam));
    return { rows: result.rows as any[] };
  }) as AkentrosQuery;
  query.dialect = "postgres";
  query.transaction = (fn: () => Promise<unknown>) =>
    db.transaction((tx) => txStorage.run({ db: tx as unknown as PGlite }, () => fn()));
  return query;
}

async function pgFixture() {
  const db = new PGlite();
  const query = createPgliteQuery(db);

  // users 與 ledger_entries 由 gateway 的 bootstrap 建立,且 core migrations 的
  // 部分唯一索引建立在 ledger_entries 之上(必須先於 AI schema 存在,
  // 與 SQLite 測試 fixture 的順序一致);此處以 PG 方言等價 DDL 建立。
  const identity = "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
  const now =
    "TEXT NOT NULL DEFAULT (to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SS.MS\"Z\"'))";
  await query(
    `CREATE TABLE IF NOT EXISTS users (
      id ${identity},
      username TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT 'user',
      balance_usd_micros INTEGER NOT NULL DEFAULT 0,
      is_banned INTEGER NOT NULL DEFAULT 0,
      is_flagged INTEGER NOT NULL DEFAULT 0,
      restricted_services TEXT NOT NULL DEFAULT '[]',
      display_name TEXT NOT NULL DEFAULT '',
      created_at ${now},
      updated_at ${now}
    )`,
  );
  await query(
    `CREATE TABLE IF NOT EXISTS ledger_entries (
      id ${identity},
      user_id INTEGER NOT NULL,
      user_name TEXT NOT NULL DEFAULT '',
      user_email TEXT NOT NULL DEFAULT '',
      direction TEXT NOT NULL,
      amount TEXT NOT NULL,
      balance_before TEXT NOT NULL,
      balance_after TEXT NOT NULL,
      transaction_type TEXT NOT NULL,
      source_type TEXT NOT NULL,
      source_id TEXT NOT NULL,
      idempotency_key TEXT,
      description TEXT NOT NULL DEFAULT '',
      metadata TEXT NOT NULL DEFAULT '{}',
      created_at ${now}
    )`,
  );

  await migrateAkentrosSchema(query);

  const user = await query(
    `INSERT INTO users (username, email, password_hash, balance_usd_micros)
     VALUES ('pg-user', 'pg@example.com', 'x', 1000000) RETURNING id, balance_usd_micros`,
  );
  const userId = String(rowsOf(user)[0].id);
  const key = await query(
    `INSERT INTO ai_api_keys (user_id, name, key_prefix, key_suffix, key_digest)
     VALUES (?, 'pg key', 'pg-prefix', 'ff', ?) RETURNING id`,
    [userId, "e".repeat(64)],
  );
  const apiKeyId = String(rowsOf(key)[0].id);
  return { query, userId, apiKeyId };
}

const rowsOf = (result: any): any[] => (Array.isArray(result?.rows) ? result.rows : []);

const fingerprint = "b".repeat(64);

test("PG dialect: versioned migration runs and is idempotent", async () => {
  const { query } = await pgFixture();
  const second = await migrateAkentrosSchema(query);
  assert.equal(second.migrated, false);
});

test("PG dialect: billing reserve, settle and refund track the ledger chain", async () => {
  const { query, userId, apiKeyId } = await pgFixture();
  const store = createAkentrosBillingStore(query);

  const reserved = await store.reserve({
    requestId: "req_pg_1",
    userId,
    apiKeyId,
    idempotencyKey: null,
    requestFingerprint: fingerprint,
    publicModel: "akentros-test-model",
    pricingRevision: "pricing-v1",
    reservedCostMicros: "8",
    expiresAt: "2030-01-01T00:00:00.000Z",
  });
  assert.equal(reserved.status, "reserved");
  await store.markDispatched(reserved.requestId);

  const settled = await store.settle({
    requestId: reserved.requestId,
    actualCostMicros: 3,
    inputTokens: 4,
    outputTokens: 2,
    usageSource: "provider",
    totalLatencyMs: 20,
  });
  assert.equal(settled.status, "succeeded");
  assert.equal(settled.chargedCostMicros, 3);
  assert.equal(settled.refundedCostMicros, 5);

  const ledger = await query(
    `SELECT direction, amount, balance_before, balance_after FROM ledger_entries ORDER BY id`,
  );
  assert.equal(rowsOf(ledger).length, 2);
  assert.equal(`${rowsOf(ledger)[0].direction} ${rowsOf(ledger)[0].amount}`, "debit 8");
  assert.equal(
    `${rowsOf(ledger)[1].direction} ${rowsOf(ledger)[1].amount} ${rowsOf(ledger)[1].balance_before} ${rowsOf(ledger)[1].balance_after}`,
    "credit 5 999992 999997",
  );
  const userRow = await query(`SELECT balance_usd_micros FROM users WHERE id = ?`, [userId]);
  assert.equal(String(rowsOf(userRow)[0].balance_usd_micros), "999997");
});

test("PG dialect: zero reported cost cannot settle a non-zero reservation", async () => {
  const { query, userId, apiKeyId } = await pgFixture();
  const store = createAkentrosBillingStore(query);
  const reserved = await store.reserve({
    requestId: "req_pg_zero",
    userId,
    apiKeyId,
    idempotencyKey: null,
    requestFingerprint: fingerprint,
    publicModel: "akentros-test-model",
    pricingRevision: "pricing-v1",
    reservedCostMicros: "8",
    expiresAt: "2030-01-01T00:00:00.000Z",
  });
  await store.markDispatched(reserved.requestId);
  await assert.rejects(
    store.settle({
      requestId: reserved.requestId,
      actualCostMicros: 0,
      inputTokens: 0,
      outputTokens: 0,
      usageSource: "provider",
      totalLatencyMs: 1,
    }),
    (error: any) => error.status === 409 && error.code === "invalid_billing_state",
  );
});

test("PG dialect: idempotency replay returns the original request", async () => {
  const { query, userId, apiKeyId } = await pgFixture();
  const store = createAkentrosBillingStore(query);
  const input = {
    requestId: "req_pg_idem",
    userId,
    apiKeyId,
    idempotencyKey: "pg-idem-1",
    requestFingerprint: fingerprint,
    publicModel: "akentros-test-model",
    pricingRevision: "pricing-v1",
    reservedCostMicros: "8",
    expiresAt: "2030-01-01T00:00:00.000Z",
  };
  const first = await store.reserve(input);
  const replay = await store.reserve(input);
  assert.equal(replay.aiRequestId, first.aiRequestId);
  assert.equal(replay.idempotentReplay, true);
  await assert.rejects(
    store.reserve({ ...input, requestFingerprint: "c".repeat(64) }),
    (error: any) => error.code === "idempotency_conflict",
  );
});

test("PG dialect: provider pool sync, claim and release roundtrip", async () => {
  const { query } = await pgFixture();
  const store = createAkentrosProviderPoolStore(query);
  await store.sync(PROVIDER_POOLS);

  const poolId = Object.keys(PROVIDER_POOLS.pools)[0];
  const claim = await store.claim({
    poolId,
    requestId: "req_pg_pool",
    leaseTtlMs: 60_000,
  });
  assert.ok(claim, "an enabled credential should be claimable");
  assert.equal(claim!.poolId, poolId);

  const released = await store.release({
    leaseId: claim!.leaseId,
    success: true,
    latencyMs: 42,
    selection: PROVIDER_POOLS.pools[poolId].selection,
  });
  assert.ok(released);

  // 健康退避路徑(指數退避 + EWMA)也應在 PG 方言下寫入。
  const claim2 = await store.claim({ poolId, requestId: "req_pg_pool_2", leaseTtlMs: 60_000 });
  assert.ok(claim2);
  await store.release({
    leaseId: claim2!.leaseId,
    success: false,
    category: "provider_error",
    latencyMs: 100,
    retryAfter: 0,
    selection: PROVIDER_POOLS.pools[poolId].selection,
  });
  const state = await query(
    `SELECT state, consecutive_failures FROM ai_provider_credentials WHERE credential_id = ?`,
    [claim2!.credentialId],
  );
  assert.equal(Number(rowsOf(state)[0].consecutive_failures), 1);
});

test("PG dialect: key RPM and in-flight admission control", async () => {
  const { query, apiKeyId } = await pgFixture();
  await query(`UPDATE ai_api_keys SET rpm_limit = 2, max_in_flight = 1 WHERE id = ?`, [apiKeyId]);
  const store = createAkentrosApiLimitStore(query);

  const first = await store.acquire({
    apiKeyId,
    requestId: "req_pg_adm_1",
    rpmLimit: 2,
    maxInFlight: 1,
    leaseTtlMs: 60_000,
  });
  assert.equal(first.requestId, "req_pg_adm_1");

  // 併發上限 1:第二個請求 429。
  await assert.rejects(
    store.acquire({ apiKeyId, requestId: "req_pg_adm_2", rpmLimit: 2, maxInFlight: 1, leaseTtlMs: 60_000 }),
    (error: any) => error.code === "max_in_flight_exceeded",
  );

  await store.release("req_pg_adm_1");
  const second = await store.acquire({
    apiKeyId,
    requestId: "req_pg_adm_2",
    rpmLimit: 2,
    maxInFlight: 1,
    leaseTtlMs: 60_000,
  });
  assert.equal(second.requestId, "req_pg_adm_2");

  await store.release("req_pg_adm_2");

  // RPM 2 已用滿(adm_1 + adm_2):租約釋放後仍被視窗計數擋下。
  await assert.rejects(
    store.acquire({ apiKeyId, requestId: "req_pg_adm_3", rpmLimit: 2, maxInFlight: 1, leaseTtlMs: 60_000 }),
    (error: any) => error.code === "rate_limit_exceeded",
  );
});
